### ISSUE TITLE
What is cd_target

### ISSUE THREAD

**Issue by dreamyou070** [yhZhai/mcm#1]
in the training code, there is cd_target argument.
can you explain what it is ~?

**Comment by yhZhai** [comment]
Hi there, thank you for your interest in our work!

cd_target refers to the different **c**onsistency **d**istillation **target** (see [our paper](https://arxiv.org/abs/2406.06890) Sec 3.2), it is defined here https://github.com/yhZhai/mcm/blob/d210332490cfbcb6bc9c71a57dd1091907e5b16d/args.py#L402

**Comment by dreamyou070** [comment]
so much thanks for the answer, 
i want to know that model name "ViT-g-14" does not correspondent to "weights/open_clip_pytorch_model.bin"
Can you check once.. ?

Thanks!

**Comment by yhZhai** [comment]
Hi there,

The CLIP model is downloaded with this [script](https://github.com/yhZhai/mcm/blob/d210332490cfbcb6bc9c71a57dd1091907e5b16d/scripts/download.py#L24), where the CLIP model checkpoint is named as `open_clip_pytorch_model.bin`. Please find more details from [the original repo](https://huggingface.co/laion/CLIP-ViT-g-14-laion2B-s34B-b88K/tree/main).
