### ISSUE TITLE
About mlp for motion consistency.

### ISSUE THREAD

**Issue by Jiexuanz** [yhZhai/mcm#10]
Can release the pretrained weight of mlp(Learnable representatio) for motion consistency model.
I only find lora weights in huggingface.

**Comment by yhZhai** [comment]
Thank you for your interest in our paper! Unfortunately, we did not save the MLP weight in the final checkpoint. That being said, we saved MLP weights during the intermediate training stage. Could you please let me know which version of MCM you need the most, and I can provide the corresponding weights.

**Comment by yhZhai** [comment]
Please find our AnimateDiff-LAIO version weight at this box link: https://buffalo.box.com/s/cnc9oltyerlk1id0xis0hgqrd1fz3clc

This is the model weight and states 500 steps before the training ends, and should achieve similar results as the final model.
