### ISSUE TITLE
How to accelerate my own text to video model? 

### ISSUE THREAD

**Issue by AdvancedHe** [yhZhai/mcm#2]
Thanks for your awesome work!
If I want to accelerate my own t2v model use this repository, how should I do? Which configuration files should I modify? I hope you can give me some advice, thanks a lot!

**Comment by yhZhai** [comment]
Hi there, I think you may need to make two major changes: 1. organize your dataset following the webdataset format (see [our guideline](https://github.com/yhZhai/mcm?tab=readme-ov-file#data-preparation-)), and 2. define and modify the teacher and student models in `main.py`.

I believe most of the training code does not require major changes.

Thanks!

**Comment by AdvancedHe** [comment]
Thanks for your guidance! I will take this steps later.
