### ISSUE TITLE
Confusing unets

### ISSUE THREAD

**Issue by dreamyou070** [yhZhai/mcm#3]
confusing with code....

there are many unet models like
unet / target_unet / teacher_unet...

I am so confusing
for example in 1495 line, unet (which to be learned) forward is with torch.no_grad...

I thinks
teacher unet previous timestep (more noisy) output is equal to unet timestep output...
(this is distill,,, isn't it?)

**Comment by yhZhai** [comment]
Hi there, sorry for the confusion, let me provide an explanation.

1. We only train LoRA as the MCM, thus `args.use_lora` is always True.
2. We follow [LCM LoRA](https://github.com/huggingface/diffusers/blob/main/examples/consistency_distillation/train_lcm_distill_lora_sd_wds.py) to use the same parameter for the student and target UNets. This means `unet` with `torch.no_grad()` is the target UNet and `unet` without `torch.no_grad()` is the student UNet.
3. `target_unet` is defined when `args.use_lora` is set to False, where EMA is used to update its parameters. We actually did not use it, but only keeps it for future usage.
