### ISSUE TITLE
Can realse your traing dataset?Thanks

### ISSUE THREAD

**Issue by songyang86** [yhZhai/mcm#4]

**Comment by shaoshitong** [comment]
You can find webvid-2M in

Train: https://anon-datasets.s3.amazonaws.com/results_2M_train.csv

Val: https://anon-datasets.s3.amazonaws.com/results_2M_val.csv

Then, you can utilize `video2dataset` to download the total dataset

**Comment by songyang86** [comment]
great,Thanks
