### ISSUE TITLE
Can we adjust the resolution of generating video?

### ISSUE THREAD

**Issue by HY-2837** [yhZhai/mcm#8]
Thanks for your awesome work!
I have a question about the video resolution. In the code, the generated video is 256 * 266. Can we adjust the resolution if we use mcm to accelerate my own text to video model? If it is true, how should I do?
Thanks a lot!
Best regards.

**Comment by yhZhai** [comment]
Hi there, our MCM supports different resolutions.

For training, you can simply adjust the `--resolution` argument (for example, [here](https://github.com/yhZhai/mcm/blob/d210332490cfbcb6bc9c71a57dd1091907e5b16d/scripts/animatediff_distillation.sh#L17) for animatediff).

For inference, you can add argument `height={your-desired-height}, width={your-desired-width}` in the [pipeline call](https://github.com/yhZhai/mcm/blob/d210332490cfbcb6bc9c71a57dd1091907e5b16d/demo.py#L42). You can check our huggingface demo for more details at [here](https://huggingface.co/spaces/yhzhai/mcm/blob/2176dd5df5f00d6276b49423b5d4acd56bafe5a2/app.py#L259).

**Comment by HY-2837** [comment]
Now, the resolution is 256 * 256, I want to adjust: 320 * 256 or any other non-square size. Is it possible?

**Comment by HY-2837** [comment]
> Hi there, our MCM supports different resolutions.
> 
> For training, you can simply adjust the `--resolution` argument (for example, [here](https://github.com/yhZhai/mcm/blob/d210332490cfbcb6bc9c71a57dd1091907e5b16d/scripts/animatediff_distillation.sh#L17) for animatediff).
> 
> For inference, you can add argument `height={your-desired-height}, width={your-desired-width}` in the [pipeline call](https://github.com/yhZhai/mcm/blob/d210332490cfbcb6bc9c71a57dd1091907e5b16d/demo.py#L42). You can check our huggingface demo for more details at [here](https://huggingface.co/spaces/yhzhai/mcm/blob/2176dd5df5f00d6276b49423b5d4acd56bafe5a2/app.py#L259).

OKKK, thanks a lot! It is very helpful for me!
