### ISSUE TITLE
The detail about accelerate my own t2v model

### ISSUE THREAD

**Issue by HY-2837** [yhZhai/mcm#9]
Hi, Yuanhao, thanks for your tips. I have some detailed question about accelerate my own t2v model.

The model I want to accelerate is [VideoCrafter2](https://github.com/AILab-CVC/VideoCrafter). The biggest problem is VC2 doesn't use diffusers lib define its model. So, I have some questions in train and inference stage.

1. Train stage:
According to your tip, I have build my own webdataset-format dataset.
Modify model: I use vc2's code ([vc2_model_define](https://github.com/AILab-CVC/VideoCrafter/blob/11bcd76fc62fb98b9715b994afe45b4fa081120c/scripts/evaluation/inference.py#L49C1-L49C31)) and extract its unet model, what I still modify next?

2. Inference stage:
What I should modify in the demo.py, so that I can inference with my own t2v model?

Thanks a lot.

**Comment by HY-2837** [comment]
Could you give me some tips?
Thanks a lot!

**Comment by yhZhai** [comment]
Hi there, I did not try VideoCrafter before, but here are some general advice.

For training, I think modifying the dataset and the model definition is enough. Please be sure to check the noise schedulers, which can be critical for distillation.
For inference, you may need to adapt VideoCrafter's code for the model definition and the noise scheduler for the multi-step sampling.

**Comment by HY-2837** [comment]
Ok, I know what you mean. 
Videocraft2 does not use the diffusers lib to define unet, therefore, some inputs need to be rewritten to adapt to VC2's Unet input
Now I am solving these problems.
Thanks a lot.
